name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

      - name: Build Docker image
        run: docker build -t nairolfln/pickem-front .

      - name: Log in to Docker Hub (if using Docker Hub for registry)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to registry (if using Docker Hub)
        run: docker push nairolfln/pickem-front:latest

      - name: SSH into deployment server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          script: |
            docker stop pickem-front || true
            docker rm pickem-front || true
            docker pull nairolfln/pickem-front:latest
            docker run -d --name pickem-front -p 4300:4300 nairolfln/pickem-front:latest